javascript_compressor: "closure"

javascripts:
    general:
        - public/javascripts/jquery.js
        - public/javascripts/jquery.ui.js
        - public/javascripts/rails.js
        - public/javascripts/application.js
        - public/javascripts/jquery.query.js
        - public/javascripts/jquery.url.js
        - public/javascripts/staff_order_by.js
        - public/javascripts/tabs.js
        
stylesheets:
    public:
         - public/stylesheets/compiled/screen.css
    print:
         - public/stylesheets/compiled/print.css
    staff:
         - public/stylesheets/staff/main.css
         - public/stylesheets/staff/general.css
         - public/stylesheets/staff/navigation.css
         - public/stylesheets/staff/tabbed_navigation.css
         - public/stylesheets/staff/forms.css
         - public/stylesheets/staff/page_styles.css
         - public/stylesheets/staff/pagination.css

        
